apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/
secretGenerator:
- name: app-tls
  files:
    - secrets/tls.cert
    - secrets/tls.key
  type: Opaque
- name: env-file-secret
  env: env.txt
  type: Opaque
